steps:

# fetch GKE cluster credentials to be used for helm step
- name: 'gcr.io/cloud-builders/kubectl'
  env:
  - 'CLOUDSDK_COMPUTE_REGION=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=betabank-autopilot-cluster-1-dev'
  - 'CLOUDSDK_CORE_PROJECT=us-con-gcp-npr-0000361-050922'
  - 'KUBECONFIG=/workspace/.kube/config'
  args: ['cluster-info']

# run helm command to install/upgrade filebeat
# optionally you can set to add any other Helm chart repository
# to use charts from
- name: 'gcr.io/$PROJECT_ID/helm:latest'
  args: ['upgrade', '--install', 'keycloak/keycloak']
  env:
  - 'KUBECONFIG=/workspace/.kube/config'
  - 'HELM_REPO_NAME=keycloak'
  - 'HELM_REPO_URL=https://betafinancialservices.github.io/keycloak-helm-repo/charts/'
  #- 'TILLERLESS=true'
  #- 'TILLER_NAMESPACE=test'
  
options:
 logging: CLOUD_LOGGING_ONLY
 pool:
    name: 'projects/$PROJECT_ID/locations/us-central1/workerPools/beta1-dev-workerpool-01'
